export default {
  lottery: {
    title: 'Lucky Draw', description: 'Join ModelPort campaigns for balance and subscription rewards', activities: 'Campaigns', history: 'History',
    refresh: 'Refresh campaigns', emptyTitle: 'No available campaigns', emptyDescription: 'New campaigns will appear here', loadFailed: 'Failed to load campaigns', retry: 'Retry',
    mode: { instant: 'Instant draw', scheduled: 'Scheduled draw' },
    state: { draft: 'Draft', not_started: 'Not started', active: 'Active', paused: 'Paused', awaiting_draw: 'Awaiting draw', ended: 'Ended', completed: 'Completed' },
    entryStatus: { pending: 'Awaiting draw', won: 'Winner', not_won: 'Not selected' },
    startsAt: 'Starts', endsAt: 'Ends', drawAt: 'Draw time', prizes: 'Prizes', balancePrize: 'Balance ￥{amount}',
    subscriptionPrize: '{days}-day subscription code', inventory: '{remaining}/{total} remaining', probability: '{value}% chance',
    attempts: '{remaining}/{total} attempts left', entryCount: '{count} entries', participate: 'Participate', participating: 'Submitting...',
    eligibility: { not_started: 'Campaign has not started', paused: 'Campaign is paused', awaiting_draw: 'Awaiting draw', ended: 'Campaign has ended', completed: 'Campaign completed', limit_reached: 'No attempts remaining', minimum_balance: 'Account balance is below the requirement', subscription_required: 'An eligible subscription is required', user_inactive: 'Account cannot participate', draft: 'Campaign is not published' },
    result: { title: 'Draw result', wonTitle: 'You won', noWinTitle: 'Not selected this time', noWinDescription: 'Thanks for participating. Another voyage awaits.', balance: '￥{amount} was added to your balance', code: 'You received {name}', copyCode: 'Copy code', redeemCode: 'Redeem now', pendingTitle: 'Entry submitted', pendingDescription: 'Your entry is recorded. Wait for the scheduled draw.', replayed: 'The original result for this request was returned', close: 'Close' },
    historyEmptyTitle: 'No participation history', historyEmptyDescription: 'Campaign results and rewards will appear here', participatedAt: 'Participated', resolvedAt: 'Resolved',
    errors: { LOTTERY_NOT_STARTED: 'Campaign has not started', LOTTERY_ENDED: 'Campaign has ended', LOTTERY_UNAVAILABLE: 'Campaign is currently unavailable', LOTTERY_INELIGIBLE: 'This account is not eligible', LOTTERY_LIMIT_REACHED: 'No attempts remaining', LOTTERY_IDEMPOTENCY_KEY_INVALID: 'Invalid request identifier. Refresh and retry.' },
    admin: {
      title: 'Lottery Management', description: 'Manage instant and scheduled draws and reward delivery', create: 'New campaign', search: 'Search campaigns', allModes: 'All modes', allStatuses: 'All statuses', emptyTitle: 'No lottery campaigns', emptyDescription: 'Create the first native lottery campaign', campaign: 'Campaign', window: 'Window', progress: 'Entries and prizes', status: 'Status', actions: 'Actions', edit: 'Edit campaign', delete: 'Delete campaign', entries: 'Entries', draw: 'Run draw', drawing: 'Drawing...', pause: 'Pause', activate: 'Activate', complete: 'Complete', draft: 'Move to draft', hasEntries: 'Campaigns with entries can no longer change configuration or prizes',
      editor: { createTitle: 'Create lottery campaign', editTitle: 'Edit lottery campaign', name: 'Campaign name', description: 'Description', mode: 'Draw mode', status: 'Initial status', startsAt: 'Start time', endsAt: 'End time', drawAt: 'Draw time', perUserLimit: 'Attempts per user', minimumBalance: 'Minimum balance', requiredGroups: 'Eligible subscriptions', noGroupRequired: 'No subscription required', prizes: 'Prize configuration', addPrize: 'Add prize', prizeName: 'Prize name', prizeType: 'Prize type', balance: 'Balance', subscriptionCode: 'Subscription code', balanceAmount: 'Balance amount', subscriptionGroup: 'Subscription group', validityDays: 'Validity days', probabilityBps: 'Probability (bps)', inventory: 'Inventory', enabled: 'Enabled', probabilityTotal: 'Enabled total {bps}/10000 ({percent}%)', probabilityExceeded: 'Enabled prize probability cannot exceed 10000 bps', removePrize: 'Remove prize', cancel: 'Cancel', save: 'Save campaign', saving: 'Saving...', invalidWindow: 'End time must be later than start time', drawBeforeEnd: 'Draw time cannot be earlier than the campaign end', required: 'Complete the campaign and prize configuration' },
      entryDialog: { title: 'Campaign entries', user: 'User', result: 'Result', reward: 'Reward', time: 'Time', empty: 'No entries yet' },
      drawConfirmTitle: 'Confirm draw', drawConfirmMessage: 'Run the draw for “{name}”? Completed draws and rewards cannot be reversed.',
      drawResult: 'Draw completed: {participants} entries, {winners} winners', deleteTitle: 'Delete campaign', deleteMessage: 'Delete “{name}”? This cannot be undone.', saved: 'Campaign saved', statusUpdated: 'Campaign status updated', deleted: 'Campaign deleted',
      errors: { LOTTERY_HAS_ENTRIES: 'Campaigns with entries cannot change prizes or be deleted', LOTTERY_INVALID_TRANSITION: 'This status transition is not allowed', LOTTERY_ENDED: 'Expired campaigns cannot be reactivated', LOTTERY_PROBABILITY_EXCEEDED: 'Enabled prize probability cannot exceed 10000 bps', LOTTERY_ALREADY_DRAWN: 'This campaign has already been drawn', LOTTERY_INVALID: 'Campaign configuration is incomplete or invalid' },
    },
  },
}
